// Generates Allstar-City content from the original Allstar-Scape v2 sources in allstar/legacy.
//
//   node allstar/tools/generate.mjs
//
// Each step in allstar/tools/gen/ receives a shared context. Re-runnable: map line edits are
// tracked in allstar/generated/maps-manifest.json and generated files are rewritten every run.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { Legacy } from './lib/legacy.mjs';
import { MapEditor } from './lib/mapedit.mjs';
import { Pack } from './lib/pack.mjs';
import steps from './gen/index.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const CONTENT = path.join(ROOT, 'content');
const GENERATED = path.join(ROOT, 'allstar/generated');
const SCRIPTS_OUT = path.join(CONTENT, 'scripts/allstar/generated');

fs.mkdirSync(GENERATED, { recursive: true });

const report = [];
const ctx = {
    root: ROOT,
    content: CONTENT,
    legacy: new Legacy(path.join(ROOT, 'allstar/legacy')),
    packs: {
        npc: new Pack(path.join(CONTENT, 'pack/npc.pack')),
        obj: new Pack(path.join(CONTENT, 'pack/obj.pack')),
        loc: new Pack(path.join(CONTENT, 'pack/loc.pack')),
        inv: new Pack(path.join(CONTENT, 'pack/inv.pack'))
    },
    maps: new MapEditor(path.join(CONTENT, 'maps'), path.join(GENERATED, 'maps-manifest.json')),
    report: (...lines) => report.push(...lines),

    // Writes content/scripts/allstar/generated/<relative>; use configs/ or scripts/ subfolders.
    writeGenerated(relative, lines) {
        const file = path.join(SCRIPTS_OUT, relative);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, ['// Generated by allstar/tools/generate.mjs - do not edit.', ...lines].join('\n') + '\n');
    }
};

for (const step of steps) {
    await step(ctx);
}

ctx.maps.save();
for (const pack of Object.values(ctx.packs)) {
    pack.save();
}

fs.writeFileSync(path.join(GENERATED, 'report.txt'), report.join('\n') + '\n');
console.log(report.join('\n'));
